name: Build
on: [push]
jobs:
  build_for_mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '20'
      - name: Install Yarn packages
        run: yarn install
      - name: Build the app
        run: yarn make
        timeout-minutes: 10
      - uses: actions/upload-artifact@v3
        with:
          name: mac_build
          path: out/make/*
  build_for_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '20'
      - name: Install Yarn packages
        run: yarn install
      - name: Build the app
        run: yarn make
        timeout-minutes: 10
      - uses: actions/upload-artifact@v3
        with:
          name: linux_build
          path: out/make/*

