name: Build
on: [push, pull_request]
jobs:
  build_on_mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '20'
      - name: Install Yarn packages
        run: yarn install
      - name: Build the app
        run: yarn make
        timeout-minutes: 5

